
import requests
import base64
import json
import argparse
import os
from datetime import datetime, timezone
from token_exchanger import get_access_token


token = get_access_token()  # <--- NEW: generates token via JWT

    # Epic FHIR Base URL
EPIC_FHIR_BASE = "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4"

def get_access_token_from_file(token_file="epic_token.txt"):
    """Reads the raw bearer token from the text file generated by Get-EpicToken.ps1"""
    if not os.path.exists(token_file):
        raise FileNotFoundError(f"Token file '{token_file}' not found. Run Get-EpicToken.ps1 first.")
    with open(token_file, "r", encoding="utf-8") as f:
        token = f.read().strip()
    if not token:
        raise ValueError("Token file is empty.")
    return token

def get_patient_encounter(access_token, patient_id):
    url = f"{EPIC_FHIR_BASE}/Encounter"
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/fhir+json"
    }
    params = {"subject": f"Patient/{patient_id}", "_count": 1}
    resp = requests.get(url, headers=headers, params=params)
    if resp.status_code == 200:
        bundle = resp.json()
        if bundle.get("entry"):
            enc_id = bundle["entry"][0]["resource"]["id"]
            print(f"✅ Found Encounter ID: {enc_id}")
            return enc_id
        else:
            raise Exception(f"No encounters found for Patient/{patient_id}")
    else:
        raise Exception(f"Encounter fetch failed: {resp.status_code} - {resp.text}")

def write_document_reference_to_epic(access_token, patient_id, summary):
    clean_patient_id = str(patient_id).replace("Patient/", "")
    encounter_id = get_patient_encounter(access_token, clean_patient_id)
    
    summary_b64 = base64.b64encode(summary.encode("utf-8")).decode("utf-8")
    
    doc_ref = {
        "resourceType": "DocumentReference",
        "status": "current",
        "docStatus": "final",


        "type": {
            "coding": [{
            "system": "http://loinc.org",
            "code": "18842-5",
            "display": "Clinical Note"
            }]
        },


        "subject": {"reference": f"Patient/{clean_patient_id}"},
        "date": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "content": [{
            "attachment": {
                "contentType": "text/plain",
                "data": summary_b64
            }
        }],
        "context": {
            "encounter": [{"reference": f"Encounter/{encounter_id}"}]
        }
    }
    
    url = f"{EPIC_FHIR_BASE}/DocumentReference"
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/fhir+json",
        "Accept": "application/fhir+json",
        "Prefer": "return=representation"
    }
    
    print(f"🚀 POSTing to Epic for Patient/{clean_patient_id}...")
    response = requests.post(url, headers=headers, json=doc_ref)
    
    if response.status_code in [200, 201]:
        created = response.json()
        doc_id = created.get("id", "unknown")
        print(f"✅ Epic write success! DocumentReference ID: {doc_id}")
        return doc_id
    else:
        print(f"❌ Epic write failed: {response.status_code}")
        print(response.text)
        response.raise_for_status()

def load_summary_file(filepath: str):
    with open(filepath, "r", encoding="utf-8") as f:
        record = json.load(f)
    if "patient_id" not in record or "summary" not in record:
        raise ValueError(f"{filepath} missing required fields.")
    return record["patient_id"], record["summary"]

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    

    parser.add_argument("summary_file", help="Path to summary_output.json")
    parser.add_argument("--patient_id", help="Override patient ID from file")
    args = parser.parse_args()


    token = get_access_token()
    patient_id, summary = load_summary_file(args.summary_file)
    if args.patient_id:
        patient_id = args.patient_id
    
    #token = get_access_token_from_file()  # <--- NEW: auto-loads epic_token.txt
    #parser.add_argument("--patient_id", help="Override patient ID from summary file")
    #args = parser.parse_args()

    patient_id, summary = load_summary_file(args.summary_file)
    if args.patient_id:
        patient_id = args.patient_id
    write_document_reference_to_epic(token, patient_id, summary)

"""
With the DocumentReference ID: XXXXXXXX

Open browser and run this code - HAPI

https://r4.smarthealthit.org/DocumentReference/XXXXXXXX

https://r4.smarthealthit.org/DocumentReference/4739676


Open browser and run this code - EPIC FHIR
✅ Epic write success! DocumentReference ID: e8aJma2uHU4A7MPcx4YplGA3

https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/DocumentReference/e8aJma2uHU4A7MPcx4YplGA3

"""